### ISSUE TITLE
players endpoint not responding

### ISSUE THREAD

**Issue by kitsunekyo** [nexus-devs/nexushub-client#3]
hitting `api.nexus-stats.com/warframe/v1/players/USERNAME/profile` results in a 504 Gateway Time-out.

is this not implemented or whats going on here? There is no documentation on whether this endpoint requires authentication, in which case it should return a 40X type error response instead of timing out.

`/warframe/v1/items/distribution`    
`/warframe/v1/items/prices`   

return a 404 response, but are used like this in the package (ie `.getItemDistribution`) without any parameters. which makes me wonder if this package might be deprecated completely.

**Comment by Kaptard** [comment]
Sorry, this endpoint has been temporarily removed until we find a more reliable tracking solution.

`/warframe/v1/items/distribution` moved to `/warframe/v1/items?data=distribution` and
`/warframe/v1/items/prices` moved to `/warframe/v1/items?data=prices`

However those endpoints will change again soon as we move towards the final API overhaul that will be used for our rework. That will also include a proper documentation page generated from our code, so you needn't rely on the outdated google doc that we put out there some time ago.

This package isn't necessarily deprectated, just outdated, because I'm doing these things mostly on my own and other parts of the project have taken higher priority. But I'll make sure to update it once the new API is out.

**Comment by kitsunekyo** [comment]
ah good to know, thanks a lot for the insight and dont worry. any documentation is better than no docu :P

did `api.nexus-stats.com/warframe/v1/players/USERNAME/profile` ever work? 
i'm desperately looking for user data endpoints for warframe for my own proof of concept things to potentially contribute to existing project, but couldnt find anything about having player data exposed.

**Comment by Kaptard** [comment]
Yes it worked, but only 70-80% of the time. It's also not very scalable, as we really just literally read the data from a game instance via OCR (that took ~10s on average). We will definitely introduce it again in the future when we made sure it'll scale, but it will be some time until then (I'm guessing 6 months minimum)

**Comment by Kaptard** [comment]
@kitsunekyo 
I should probably also mention that the player tracking bot's code is still [available here](https://github.com/nexus-devs/nexus-sentry/tree/master/lib/ondemand/players), if you wish to implement it on a small scale on your own.

It requires a dedicated VM just running Warframe and Tesseract (I'd recommend 3.x) [Link to Windows binaries](https://digi.bib.uni-mannheim.de/tesseract/).

That code is tied in with our API servers, so you'll have to restructure it a little, but just calling `PlayerSentry.getPlayer('username')` should give you all the data. It assumes you're running Warframe in 1080p with the chat window open in full size. Make sure you're not in some actual chat though, it *will* sometimes fail and write random stuff to the chat instead of doing the `/profile <username>`.

**Comment by Kaptard** [comment]
Updated this package - everything should be up to date now. You can check out the auto-generated API docs [over here](https://staging.nexushub.co/developers). Since it's all on staging only right now, I recommend connecting there as noted in the readme.

This *should* also work on the old API, if you need any resources from there that aren't covered on the rework yet.
